# Discretization of Continuous Numerical Data

* Numerical data is divided into distinct intervals.
* Through discretization, numerical features can be converted into categorical data.
* `Discretization` refers to the process of transforming a continuous variable into a variable with two or more categories.

In [1]:
import numpy as np
import pandas as pd

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

# Using Numpy

### `np.digitize()`
A method for dividing numerical features based on multiple threshold values.
* The input value for the `bins` parameter represents the left boundary of each interval.
* If you set `bins = [20, 35, 65]`, the data is divided into 4 intervals: `[~ 20)`, `[20, 35)`, `[35, 65)`, `[65 ~)`.
* You can include the right bound to be inclusive, by setting `right = True`

In [2]:
# given data
age = [[6], [12], [20], [39], [66]]  # 2D
age

[[6], [12], [20], [39], [66]]

In [3]:
np.digitize(age, bins=[20, 35, 65])

array([[0],
       [0],
       [1],
       [2],
       [3]])

In [4]:
np.digitize(age, bins=[20, 30, 65], right=True)

array([[0],
       [0],
       [0],
       [2],
       [3]])

## `np.where()`

Discretizing Continuous Variables using `np.where(condition, factor1, factor2)`

Can be used to discretize continuous variables by applying conditions and assigning corresponding factors.

* `condition`: The condition to evaluate.
* `factor1`: The value to assign when the condition is true.
* `factor2`: The value to assign when the condition is false.

In [5]:
# age = [[6], [12], [20], [39], [66]]
# np.where(age >= 40, "high", "low")

# TypeError: '>=' not supported between instances of 'list' and 'int'

In [6]:
age = np.array([[6], [12], [20], [39], [66]])
np.where(age >= 40, "high", "low")

array([['low'],
       ['low'],
       ['low'],
       ['low'],
       ['high']], dtype='<U4')

# Using sklearn

### `Binarizer()`

Use to convert continuous variables into a binary variable with two values based on a specified threshold:

* If the value is equal to or less than the threshold, it is converted to '0'.
* If the value is greater than the threshold, it is converted to '1'.

In [7]:
from sklearn.preprocessing import Binarizer

In [8]:
binarizer = Binarizer(threshold=20)
binarizer.fit_transform(age)

array([[0],
       [0],
       [0],
       [1],
       [1]])

## `KBinsDiscretizer()`

This function divides continuous feature values into multiple intervals, and you can specify the number of intervals to divide into.

* `encode` :
    * 'onehot-dense' returns a dense array.
    * 'ordinal' returns sequential categorical values.
* `strategy`:
    * 'quantile': Ensures that each interval contains approximately the same number of data points.
    * 'uniform': Ensures that each interval has the same width.
    * 'kmeans': Values in each bin have the same nearest center of a 1D
* The values of the intervals can be checked using the `bin_edges_` attribute.

In [9]:
from sklearn.preprocessing import KBinsDiscretizer

### strategy=uniform

In [10]:
age = np.array([[0], [1], [12], [20], [39], [45], [80]])

kb = KBinsDiscretizer(4, encode="ordinal", strategy="uniform")
kb.fit_transform(age)  # 1~19, 20~39, 40~59, 60~80

array([[0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [2.],
       [3.]])

In [11]:
age = np.array([[0], [1], [12], [20], [39], [45], [80]])

kb = KBinsDiscretizer(4, encode="onehot-dense", strategy="uniform")
kb.fit_transform(age)  # 1~19, 20~39, 40~59, 60~80

array([[1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Strategy=quantile

In [12]:
age = np.array([[0], [1], [12], [20], [39], [45], [80]])

kb = KBinsDiscretizer(5, encode="ordinal", strategy="quantile")
kb.fit_transform(age)

/Users/I751244/Desktop/soop/datascience/ds101/.dsenv/lib/python3.12/site-packages/sklearn/preprocessing/_discretization.py:296: FutureWarning: The current default behavior, quantile_method='linear', will be changed to quantile_method='averaged_inverted_cdf' in scikit-learn version 1.9 to naturally support sample weight equivalence properties by default. Pass quantile_method='averaged_inverted_cdf' explicitly to silence this warning.
  warnings.warn(

array([[0.],
       [0.],
       [1.],
       [2.],
       [3.],
       [4.],
       [4.]])

In [13]:
age = np.array([[0], [1], [12], [20], [39], [45], [80]])

kb = KBinsDiscretizer(5, encode="onehot-dense", strategy="quantile")
kb.fit_transform(age)

/Users/I751244/Desktop/soop/datascience/ds101/.dsenv/lib/python3.12/site-packages/sklearn/preprocessing/_discretization.py:296: FutureWarning: The current default behavior, quantile_method='linear', will be changed to quantile_method='averaged_inverted_cdf' in scikit-learn version 1.9 to naturally support sample weight equivalence properties by default. Pass quantile_method='averaged_inverted_cdf' explicitly to silence this warning.
  warnings.warn(

array([[1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.]])

In [14]:
kb.bin_edges_

array([array([ 0. ,  3.2, 15.2, 31.4, 43.8, 80. ])], dtype=object)

In [15]:
# validate

for i in range(0, 101, 20):
    print(f"age bound of percentile {i}% : {np.percentile(age, i).round(1)}")

age bound of percentile 0% : 0.0
age bound of percentile 20% : 3.2
age bound of percentile 40% : 15.2
age bound of percentile 60% : 31.4
age bound of percentile 80% : 43.8
age bound of percentile 100% : 80.0

### Recall Discretization of Continuous Numerical Data

* Numerical data is divided into distinct intervals.
* Through discretization, numerical features can be converted into categorical data.
* Discretization refers to the process of transforming a continuous variable into a variable with two or more categories.

# Using Pandas

Binning allows converting numerical data into categorical data by categorizing the numeric values.

* `pd.cut()`: Divides the data into **uniform intervals width**, or by specifying the boundary values for the intervals.

* `pd.qcut()`: Divides the data into a specified number of intervals, ensuring each interval **contains the equal number of data points**, without explicitly specifying the boundary values.

## pd.cut() - uniform intervals width

Equal-Length Buckets Categorization

* The `pd.cut()` function allows easy categorization by taking numerical data and the interval boundaries as arguments.
* The data segmented using `pd.cut()` is returned as a Series with a categorical data type.

In [16]:
age = np.array([0, 1, 12, 20, 39, 45, 80])  # pd.cut, pd.qcut requires 1D
age

array([ 0,  1, 12, 20, 39, 45, 80])

In [17]:
cats1 = pd.cut(age, 4)
print(type(cats1))
cats1

<class 'pandas.core.arrays.categorical.Categorical'>

[(-0.08, 20.0], (-0.08, 20.0], (-0.08, 20.0], (-0.08, 20.0], (20.0, 40.0], (40.0, 60.0], (60.0, 80.0]]
Categories (4, interval[float64, right]): [(-0.08, 20.0] < (20.0, 40.0] < (40.0, 60.0] < (60.0, 80.0]]

In [18]:
df = pd.DataFrame({"value": age, "pd.cut": cats1})
df

   value         pd.cut
0      0  (-0.08, 20.0]
1      1  (-0.08, 20.0]
2     12  (-0.08, 20.0]
3     20  (-0.08, 20.0]
4     39   (20.0, 40.0]
5     45   (40.0, 60.0]
6     80   (60.0, 80.0]

### specifying boundaries possible

The function will automatically divide the data into equal intervals based on the minimum and maximum values of the data. However, you can also specify desired boundaries

The `age` data is returned as a categorical Series with 4 specified intervals

In [19]:
age = np.array([0, 1, 12, 20, 39, 45, 80])
bins = [18, 25, 35, 60, 65]

# 18 ~ 25 / 25 ~ 35 / 35 ~ 60 / 60 ~ 65 total 4 intervals
cats2 = pd.cut(age, bins)
cats2

[NaN, NaN, NaN, (18.0, 25.0], (35.0, 60.0], (35.0, 60.0], NaN]
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 65]]

In [20]:
df["pd.cuts.withbin"] = cats2
df

   value         pd.cut pd.cuts.withbin
0      0  (-0.08, 20.0]             NaN
1      1  (-0.08, 20.0]             NaN
2     12  (-0.08, 20.0]             NaN
3     20  (-0.08, 20.0]    (18.0, 25.0]
4     39   (20.0, 40.0]    (35.0, 60.0]
5     45   (40.0, 60.0]    (35.0, 60.0]
6     80   (60.0, 80.0]             NaN

### `.codes`
By using `.codes`, you can see the integer index representing which interval each element of `age` belongs to. 

For example, for categorizing case with specified interval, 20-year-old belongs to the first interval (index 0), and 39-year-old belongs to the second interval, and 1-year-old is not belonging anywhere.

In [21]:
print(cats1.codes)
print(cats2.codes)

[0 0 0 0 1 2 3]
[-1 -1 -1  0  2  2 -1]

By using `.value_counts()`, you can check the count of elements in each interval. This helps to determine how many elements belong to each category in a categorical Series.

In [22]:
print(cats1.value_counts())  # un-even value counts
print(cats2.value_counts())  # un-even value counts

(-0.08, 20.0]    4
(20.0, 40.0]     1
(40.0, 60.0]     1
(60.0, 80.0]     1
Name: count, dtype: int64
(18, 25]    1
(25, 35]    0
(35, 60]    2
(60, 65]    0
Name: count, dtype: int64

### labeling group names
When calling `pd.cut()`, you can add the `labels = [list]` argument to specify custom category labels for each interval.

In [23]:
age = np.array([0, 1, 12, 20, 39, 45, 80])

# 18 ~ 25 / 25 ~ 35 / 35 ~ 60 / 60 ~ 65 total 4 intervals
cats3 = pd.cut(age, bins=[18, 25, 35, 60, 65], labels=["A", "S", "D", "F"])
cats3

[NaN, NaN, NaN, 'A', 'D', 'D', NaN]
Categories (4, object): ['A' < 'S' < 'D' < 'F']

In [24]:
df["labels"] = cats3
df

   value         pd.cut pd.cuts.withbin labels
0      0  (-0.08, 20.0]             NaN    NaN
1      1  (-0.08, 20.0]             NaN    NaN
2     12  (-0.08, 20.0]             NaN    NaN
3     20  (-0.08, 20.0]    (18.0, 25.0]      A
4     39   (20.0, 40.0]    (35.0, 60.0]      D
5     45   (40.0, 60.0]    (35.0, 60.0]      D
6     80   (60.0, 80.0]             NaN    NaN

## pd.qcut() - equal-Size Buckets Categorization

Pandas provides a function called `qcut()`.

* It defines intervals based on the specified number of intervals (bins).
* Unlike `pd.cut()`, which divides the data based on the minimum and maximum values, 
* `pd.qcut()` takes the data distribution into account and divides the data into intervals such that each interval contains an equal number of data points, using quantiles as the bin boundaries.

In [25]:
age = np.array([0, 1, 12, 20, 39, 45, 80])
cats4 = pd.qcut(age, 4)
cats4

[(-0.001, 6.5], (-0.001, 6.5], (6.5, 20.0], (6.5, 20.0], (20.0, 42.0], (42.0, 80.0], (42.0, 80.0]]
Categories (4, interval[float64, right]): [(-0.001, 6.5] < (6.5, 20.0] < (20.0, 42.0] < (42.0, 80.0]]

* Instead of simply dividing the range between the minimum and maximum values into four equal parts, it considers the distribution and splits the data into quartiles.
* Unlike the `cut()` function, it cannot be said that each interval has the same length.

In [26]:
cats4.value_counts()

(-0.001, 6.5]    2
(6.5, 20.0]      2
(20.0, 42.0]     1
(42.0, 80.0]     2
Name: count, dtype: int64

In [27]:
df["pd.qcut"] = cats4
df

   value         pd.cut pd.cuts.withbin labels        pd.qcut
0      0  (-0.08, 20.0]             NaN    NaN  (-0.001, 6.5]
1      1  (-0.08, 20.0]             NaN    NaN  (-0.001, 6.5]
2     12  (-0.08, 20.0]             NaN    NaN    (6.5, 20.0]
3     20  (-0.08, 20.0]    (18.0, 25.0]      A    (6.5, 20.0]
4     39   (20.0, 40.0]    (35.0, 60.0]      D   (20.0, 42.0]
5     45   (40.0, 60.0]    (35.0, 60.0]      D   (42.0, 80.0]
6     80   (60.0, 80.0]             NaN    NaN   (42.0, 80.0]

In [28]:
df["qcut-label"] = pd.qcut(age, 4, labels=["q", "w", "e", "r"])
df

   value         pd.cut pd.cuts.withbin labels        pd.qcut qcut-label
0      0  (-0.08, 20.0]             NaN    NaN  (-0.001, 6.5]          q
1      1  (-0.08, 20.0]             NaN    NaN  (-0.001, 6.5]          q
2     12  (-0.08, 20.0]             NaN    NaN    (6.5, 20.0]          w
3     20  (-0.08, 20.0]    (18.0, 25.0]      A    (6.5, 20.0]          w
4     39   (20.0, 40.0]    (35.0, 60.0]      D   (20.0, 42.0]          e
5     45   (40.0, 60.0]    (35.0, 60.0]      D   (42.0, 80.0]          r
6     80   (60.0, 80.0]             NaN    NaN   (42.0, 80.0]          r

# 🍷 Wine Example

### 1. Discretize

**Objective**: Convert continuous data into categorical data. For example, discretize the `alcohol` or `flavanoids` feature in the wine dataset into different categories.

**Example**: Discretize the `alcohol` feature in the wine dataset into 3 categories.

In [29]:
from sklearn.datasets import load_wine
wine = load_wine()
df = pd.DataFrame(wine.data, columns=wine.feature_names)
df

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95.0,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740.0
174,13.40,3.91,2.48,23.0,102.0,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750.0
175,13.27,4.28,2.26,20.0,120.0,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835.0
176,13.17,2.59,2.37,20.0,120.0,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840.0
177,14.13,4.10,2.74,24.5,96.0,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560.0

In [30]:
cats = pd.cut(
    df["alcohol"],
    bins=[11, 12, 13, 15, 19],
    labels=["Low", "Medium", "High", "VeryHigh"],
)
print(cats.value_counts())
df["alcohol_discretized"] = cats
df

alcohol
High        92
Medium      64
Low         22
VeryHigh     0
Name: count, dtype: int64

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,alcohol_discretized
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0,High
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0,High
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0,High
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0,High
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95.0,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740.0,High
174,13.40,3.91,2.48,23.0,102.0,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750.0,High
175,13.27,4.28,2.26,20.0,120.0,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835.0,High
176,13.17,2.59,2.37,20.0,120.0,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840.0,High
177,14.13,4.10,2.74,24.5,96.0,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560.0,High

## Problem Questions:
The alcohol feature is divided into 3 categories: Low, Medium, and High. Check which category each wine belongs to.

Divide the alcohol feature into 5 categories: Very Low, Low, Medium, High, and Very High, and check how many wines belong to each category.

Apply the same method to the flavanoids feature, discretizing it into Low, Medium, and High. Then, check the distribution of each category.